branches:
  only:
    - master

language: ruby
rvm:
  - "2.0.0"
  - "2.1.2"

install: 
  - bundle install
    # Assure order of files for qed
script: 
  - bundle exec rspec spec
  - ./acceptance_test

