branches:
  only:
    - master

language: ruby
rvm:
  - "2.2.3"


install: 
  - bundle install
    # Assure order of files for qed
  - mkdir tmp || true
script: 
  - bundle exec rspec spec
  - HOME=/home/robert ./acceptance_test

