#!/usr/bin/env bash

function run_one_test
{
        local test_name=${1}
        local file_name=${test_name:t}
        file_name=${file_name/*\/}
        test_name=${file_name%.rb}
        file_name=${test_name}.rb

        test -r examples/$file_name || return

        echo "running $file_name"
        bundle exec ruby examples/$file_name > tmp/$test_name

        # TODO: Provide a sexier diff and colorize
        if diff examples/expectations/${test_name} tmp/$test_name
        then
          echo "OK... $test_name"
        else
          error_count=$((error_count+1))
        fi
}


( rm tmp/* ) >/dev/null 2>&1
export error_count=0

if test -z "$*"
then
  for example in examples/*.rb
  do
          run_one_test ${example}
  done
else
  for example
  do
          run_one_test ${example}
  done
fi

echo "----------------------------------------------------"
echo "$error_count errors"

test $error_count = 0
